### ISSUE TITLE
associated.txt

### ISSUE THREAD

**Issue by YJonmo** [puzzlepaint/surfelmeshing#21]
Hi there,

Thanks for this. 

I ran this command: 
python3 associate.py /home/joon/Installations/surfelmeshing-master/data/rgbd_dataset_freiburg3_sitting_static/rgb.txt /home/joon/Installations/surfelmeshing-master/data/rgbd_dataset_freiburg3_sitting_static/depth.txt > /home/joon/Installations/surfelmeshing-master/data/rgbd_dataset_freiburg3_sitting_static/associated.txt

then I ran:
./build_RelWithDebInfo/applications/surfel_meshing/SurfelMeshing /home/joon/Installations/surfelmeshing-master/data/rgbd_dataset_freiburg3_sitting_static /home/joon/Installations/surfelmeshing-master/data/rgbd_dataset_freiburg3_sitting_static/groundtruth.txt

but I got error on reading associated.txt file:
Cannot read association line!

and when I open the assoicated.txt file then I see this:
[22;0t]0;IPython: Installations/surfelmeshing-master[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m~/Installations/surfelmeshing-master/associate.py[0m in [0;36m<module>[0;34m[0m
[1;32m    117[0m     [0msecond_list[0m [0;34m=[0m [0mread_file_list[0m[0;34m([0m[0margs[0m
.
.
.

I downloaded this dataset: 
Category: Dynamic Objects
fr3/sitting_static

Any idea why associate.txt looks like this or is it in the correct format? 
Regards,
Jacob

**Comment by puzzlepaint** [comment]
This is not the expected content of the associated.txt file. There was an error executing the script `associate.py`, and it seems that the error message got written into the output file. You may run the script without the part `> /home/joon/Installations/surfelmeshing-master/data/rgbd_dataset_freiburg3_sitting_static/associated.txt`, then I think that the error message should be printed to the terminal instead (where the formatting should be better than in the file, since I guess that the special characters should translate to colors in the terminal).

The other question is why the `associate.py` script fails to run. This would be easier to say with the full error message given. Perhaps it needs to be run with the working directory set to the folder in which the files are? At least, the example in the Readme does it like that. Or perhaps it only works with Python 2?

**Comment by YJonmo** [comment]
Thanks a lot for this. The problem was that I was using the python3. So it only works on python2.

I have a question by the way, I am more interested on reconstructing the non rigid objects while the camera is not moving. Is Surfelmesh something that I should use for my problem or Elastic fusion more suitable?

**Comment by puzzlepaint** [comment]
SurfelMeshing is not designed for non-rigid objects, and if I remember correctly, neither is ElasticFusion. You should probably consider something like DynamicFusion instead.
