### ISSUE TITLE
Meshing resolution

### ISSUE THREAD

**Issue by CanCanZeng** [puzzlepaint/surfelmeshing#5]
Hi @puzzlepaint , thank you for sharing this code, it's a great job!
I tried your code on TUM RGB-D dataset and my own data, this algorithm produced wonderful result, but I found that the mesh resolution is too high, results in very large obj file. Is there any parameter to control the meshing resolution? I did not find any.

**Comment by puzzlepaint** [comment]
The meshing resolution is directly tied to the input resolution in this approach. So, to reduce the resolution, either the input images could be downsized directly, or the `--pyramid_level` parameter can be used.

Also, in case the file size of the .obj files is an issue, it might be worth trying out other formats (such as .ply for example) since .obj files are plain-text files that take up a lot of space compared to more efficient formats.

**Comment by CanCanZeng** [comment]
Thank you for your help @puzzlepaint , I will try
