### ISSUE TITLE
Compilation issue with ubuntu 16.04

### ISSUE THREAD

**Issue by pavan4** [puzzlepaint/surfelmeshing#7]
Hi @puzzlepaint, 

I did  notice you mentioned that this compiles with `Ubuntu 14.04`. I am trying  to work with `16.04`

When I compile I get the following issue  

`nvcc fatal : A single input file is required for a non-link phase when an outputfile is specified` 

in the generated cmake file for the cuda code specifically for `cuda_unprojection_lookup.cu` and  `cuda_buffer.cu` 

Any obvious fixes here? 

I tried changing cmake versions from `2.8.12, 3.2.2, 3.5.1` All have the same issue. I am on `cuda 8.0`.

**Comment by puzzlepaint** [comment]
Hi, I can't remember seeing this error before. Just a guess: are there perhaps any spaces in the paths? Maybe those aren't properly handled. Otherwise, I would try to run `VERBOSE=1 make` which should print the exact compiler invocations that are being done. Then one can try to modify the problematic ones to find out what exactly is wrong with them.

**Comment by pavan4** [comment]
It was a bug inside nvcc cmake 

Fix: find this file - `run_nvcc.cmake` usually something  like `/usr/share/cmake-3.5/Modules/FindCUDA/run_nvcc.cmake`

and change `set(nvcc_flags @nvcc_flags@)` to  `set(nvcc_flags "@nvcc_flags@")`  (add double quotes)
